nglibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('searcher.urls'))
]

searcher/urls.py
import django.views.defaults
from django.urls import path, include
from django.contrib import admin
from . import views
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'api/authors', views.AuthorsViewSet)

app_name = 'searcher'
urlpatterns = [
    path('', views.books_by_author, name='home'),
    path('api/', views.api_info, name='API'),
    path('', include(router.urls)),
    path('api/author/<str:name>/', views.author_detail),
    path('about/', views.about, name='about'),
]

searcher/models.py
from django.db import models


class Author(models.Model):
    author_key = models.CharField(max_length=50)
    personal_name = models.CharField(max_length=100)
    alternate_names = models.TextField(default='')
    view_count = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.personal_name}, {self.view_count}'

searcher/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
import requests

from .models import Author
from rest_framework import viewsets
from searcher.serializers import AuthorSerializer


def books_by_author(request):
    author_key = []
    author_work_count = int
    author_info = {}
    books = {}
    searching_result = 1
    if 'author' in request.GET:
        content = get_author_key_and_work_count(request)
        if content:
            author_key = content[0]
            author_work_count = content[1]
            author_info = get_author_info(author_key)
            books = get_author_books(author_key, author_work_count)
            count_view_for_the_author(author_key, author_info)
        else:
            searching_result = 0
    return render(request, 'searcher/home.html', {
        'author_key': author_key,
        'author_work_count': author_work_count,
        'author_info': author_info,
        'books': books,
        'searching_result': searching_result,
    })


def get_author_key_and_work_count(request):
    author = str(request.GET['author'])
    author = author.replace(' ', '+')
    url = f'https://openlibrary.org/search/authors.json?q="{author}"'
    response = requests.get(url)
    content = response.json()
    if content['numFound'] > 0:
        author_key = content['docs'][0]['key']
        author_work_count = content['docs'][0]['work_count']
        return author_key, author_work_count
    else:
        return None


def get_author_info(author_key):
    url = f'https://openlibrary.org/authors/{author_key}.json'
    response = requests.get(url)
    author_info = response.json()
    return author_info


def get_author_books(author_key, author_work_count):
    url = f'https://openlibrary.org/authors/{author_key}/works.json?limit={author_work_count}'
    response = requests.get(url)
    author_books = response.json()['entries']
    books = {}
    for book in author_books:
        title = book['title']
        openlibrary_url = f"https://openlibrary.org{book['key']}"
        books[title] = openlibrary_url
    return books


def count_view_for_the_author(author_key, author_info):
    try:
        author = Author.objects.get(author_key=author_key)
    except (KeyError, Author.DoesNotExist):
        try:
            alternate_names = author_info['alternate_names']
        except KeyError:
            alternate_names = ''

        author = Author(
            author_key=author_key,
            personal_name=author_info['personal_name'],
            alternate_names=alternate_names,
            view_count=1,
        )
        author.save()
    else:
        author.view_count += 1
        author.save()


class AuthorsViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows to get all searched authors.
    """
    queryset = Author.objects.all().order_by('-view_count')
    serializer_class = AuthorSerializer
    http_method_names = ['get']


def author_detail(request, name):
    """
    API endpoint to retrieve an author details by personal_name
    """
    try:
        author = Author.objects.get(personal_name=name)
    except Author.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        serializer = AuthorSerializer(author)
        return JsonResponse(serializer.data)


def api_info(request):
    return render(request, 'searcher/API.html')


def about(request):
    return render(request, 'searcher/about.html')

searcher/templates/searcher/API.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>API</title>
</head>
<body>
{% include "searcher/links.html" %}
<p>This app has its own API for getting statistics about searches. Main API endpoints are:</p>
<ul>
    <li>all found authors, sorted by the most searched:
        <br><a href="/api/authors/">http://.../api/authors/</a>
    </li>
    <br>
    <li>first x most searched authors:
        <br>http://.../api/authors/?limit=x
        <br>
        <br><i>for example <a href="/api/authors/?limit=3">http://.../api/authors/?limit=3</a></i>
    </li>
    <br>
    <li>specific author by name and surname:
        <br>http://.../api/author/Name%20Surname/
        <br>
        <br><i>for example <a href="/api/author/Paulo%20Coelho/">http://.../api/author/Paulo%20Coelho/</a></i>
    </li>
</ul>
</body>
</html>

searcher/templates/searcher/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
{% include "searcher/links.html" %}
<p>'NGlibrary' is the web application in Django using API of
    <a href="https://openlibrary.org/" target="_blank">Open Library</a>.
    It also has
    <a href="{% url 'searcher:API' %}">its own API</a>
     for getting statistics about searches.
</p>
Features of NGlibrary:
<ul>
    <li>user can search for the author's published books,</li>
    <li>results are collected through API of the Open Library,</li>
    <li>results can be exported to a CSV file,</li>
    <li>statistics about searched and viewed authors in this app are collected in SQL database,</li>
    <li>statistics can be read via Admin Panel,</li>
    <li>statistics are also available via API.</li>
</ul>
</body>
</html>

searcher/templates/searcher/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Searcher</title>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
        tr:nth-child(2n+1) {
            background: #ccc;
        }
    </style>
</head>

<body>
{% include "searcher/links.html" %}

<h2>Search for the author's books</h2>
<div id="search_area" style="display: flex">
    <form method="get">
        <label for="author">Author:</label>
        <input type="text" name="author" id="author" required="required" placeholder="Name Surname">
        <button type="submit" id="btn_search">Search</button>
    </form>
    <button id="btn_clear">Clear</button>
</div>
<p id="info" style="display: none; color: blue">Searching... Please wait.</p>
<div id="results">
{% if author_key %}
    <br><b>Personal name:</b> {{ author_info.personal_name }}
    <br><b>Alternate names:</b> {{ author_info.alternate_names }}
    <br><b>Date of birth:</b> {{ author_info.birth_date }}
    {% if author_info.death_date %}
        <br><b>Date of death:</b> {{ author_info.death_date }}
    {% endif %}
    {% if author_info.bio %}
        <br><b>About the author:</b> {{ author_info.bio }}
    {% endif %}
    <br>
    <br><b>{{ author_work_count }} works as follows:</b>
    <button id="download-button" style="color: blue">Download CSV file with below results</button>
    <br>
    <br>
    <table>
        <tr>
            <th>Title</th>
            <th>Openlibrary URL</th>
        </tr>
        {% for key, value in books.items %}
        <tr>
            <td>{{ key }}</td>
            <td><a href="{{ value }}" target="_blank">{{ value }}</a></td>
        </tr>
        {% endfor %}
    </table>
{% endif %}
{% if searching_result == 0 %}
    <div id="searching_result_info">
        <p style="color: red">Can't find the author. Please try again.</p>
    </div>
{% endif %}
</div>

<script>
    const textarea = document.getElementById('author');
    const clear = document.getElementById('btn_clear');
    const results = document.getElementById('results');
    const info = document.getElementById('info');
    const search = document.getElementById('btn_search');
    const previous_info = document.getElementById('searching_result_info')

    clear.addEventListener('click', function clear() {
        textarea.value = '';
        results.style.display = 'none';
    });

    search.addEventListener('click', function search() {
        if(textarea.value.length != 0 ) {
            info.style.display = 'block';
            results.style.display = 'none';
            previous_info.style.display = 'none';
        }
    });
</script>

<script>
function htmlToCSV(html, filename) {
    var data = [];
	var rows = document.querySelectorAll("table tr");

	for (var i = 0; i < rows.length; i++) {
		var row = [], cols = rows[i].querySelectorAll("td, th");

		for (var j = 0; j < cols.length; j++) {
		        row.push(cols[j].innerText);
        }

		data.push(row.join(","));
	}

	downloadCSVFile(data.join("\n"), filename);
}
</script>

<script>
function downloadCSVFile(csv, filename) {
	var csv_file, download_link;

	csv_file = new Blob([csv], {type: "text/csv"});

	download_link = document.createElement("a");

	download_link.download = filename;

	download_link.href = window.URL.createObjectURL(csv_file);

	download_link.style.display = "none";

	document.body.appendChild(download_link);

	download_link.click();
}
</script>

 <script>
document.getElementById("download-button").addEventListener("click", function () {
	var html = document.querySelector("table").outerHTML;
	htmlToCSV(html, "books_{{ author_info.personal_name }}.csv");
});
</script>
</body>
</html>

searcher/templates/searcher/links.html
<a href="{% url 'searcher:home' %}">Search</a> |
<a href="{% url 'searcher:about' %}">About</a> |
<a href="{% url 'searcher:API' %}">API</a> |
<a href="/admin/searcher/author/">Admin Panel</a>